version: 2

sources:
  - name: idnclimate
    schema: raw
    tables:
      - name: province
        identifier: raw_province

      - name: region
        identifier: raw_region

      - name: station
        identifier: raw_station

      - name: climate_data
        identifier: raw_climate_data
        # loaded_at_field: date
        # freshness:
        #   warn_after: {count: 24, period: hour}
        #   error_after: {count: 48, period: hour}